/*
 * frame1.java
 *
 * Created on August 11, 2008, 11:42 PM
 */
package debugapp;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.TreeSet;
import java.sql.*;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrator
 * 
 */
public class frame1 extends javax.swing.JFrame {

    int min, sec;
    Connection con;
    javax.swing.Timer tim;
    Iterator it;
    Random ran = new Random();
    TreeSet ts1 = new TreeSet();
    TreeSet ts2 = new TreeSet();
    TreeSet ts3 = new TreeSet();
    Statement st;
    ResultSet rs;
    Integer curr;
    PreparedStatement s, s1, s2,ps,s3;
    Integer score = 0;
    int flag = 0;
    String name;

    /** Creates new form frame1 */
    public frame1() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/debug", "root", "root");
            
            /*ps=con.prepareStatement("insert into debug.login(name,id,pass,score) values(?,?,?,?);");
            s3=con.prepareStatement("update debug.login set score=? where name=?;");*/
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        quesframe.setDefaultCloseOperation(EXIT_ON_CLOSE);


    
        initComponents();
    }


    class Listen1 implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            min = Integer.parseInt(lb1.getText());
            sec = Integer.parseInt(lb2.getText());

            if (sec == 1) {
                min = min - 1;
                sec = 59;
            } else if (sec == 0) {
                min = min - 1;
                sec = 59;
            } else {
                sec = sec - 1;
            }

            lb1.setText(new Integer(min).toString());
            lb2.setText(new Integer(sec).toString());

        }
    }

class Listen2 implements ActionListener {

       public void actionPerformed(ActionEvent e) {
          /*name=tname.getText();
        String id=tid.getText();
        String pass=new String(tpass.getPassword());
       System.out.println(tid.getText());
        System.out.println("hi");*/
        //System.out.println(name+id+pass);
        try {
            ps=con.prepareStatement("insert into login(name,id,pass,score) values(?,?,?,?);");
            s3=con.prepareStatement("update login set score=? where id=?;");
                   
            ps.setString(1, name);
            ps.setInt(4,0);
            ps.executeUpdate();
        }
        
        
        catch(SQLException ex2) {
            JOptionPane.showMessageDialog(null,ex2.getMessage());
        }
        
        
        finstr.setSize(800,600);
        finstr.getContentPane().setBackground(Color.black);
          finstr.getContentPane().setForeground(Color.white);
        finstr.setVisible(true);
        
       // this.setVisible(false);
    
        }
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quesframe = new javax.swing.JFrame();
        pques = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtq = new javax.swing.JTextArea();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        bconfirm = new javax.swing.JButton();
        bnext = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        finstr = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bstart = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bstart1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        pques.setBackground(new java.awt.Color(0, 0, 0));

        txtq.setColumns(20);
        txtq.setRows(5);
        jScrollPane1.setViewportView(txtq);

        op1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(op1);
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("jRadioButton1");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(op2);
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("jRadioButton2");

        op3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(op3);
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("jRadioButton3");

        op4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(op4);
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("jRadioButton4");

        bconfirm.setText("Submit");
        bconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bconfirmActionPerformed(evt);
            }
        });

        bnext.setText("Next");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });

        lb1.setBackground(new java.awt.Color(0, 0, 0));
        lb1.setFont(new java.awt.Font("Arial Black", 1, 14));
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("15");

        lb2.setBackground(new java.awt.Color(0, 0, 0));
        lb2.setFont(new java.awt.Font("Arial Black", 1, 14));
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setText("00");

        org.jdesktop.layout.GroupLayout pquesLayout = new org.jdesktop.layout.GroupLayout(pques);
        pques.setLayout(pquesLayout);
        pquesLayout.setHorizontalGroup(
            pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pquesLayout.createSequentialGroup()
                .add(237, 237, 237)
                .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pquesLayout.createSequentialGroup()
                        .add(57, 57, 57)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 392, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(45, 45, 45)
                        .add(lb1)
                        .add(10, 10, 10)
                        .add(lb2))
                    .add(pquesLayout.createSequentialGroup()
                        .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pquesLayout.createSequentialGroup()
                                .add(126, 126, 126)
                                .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(op3)
                                    .add(op1))
                                .add(77, 77, 77))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pquesLayout.createSequentialGroup()
                                .add(bconfirm)
                                .add(74, 74, 74)))
                        .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(op2)
                            .add(op4)
                            .add(bnext))))
                .addContainerGap(1986, Short.MAX_VALUE))
        );
        pquesLayout.setVerticalGroup(
            pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pquesLayout.createSequentialGroup()
                .add(229, 229, 229)
                .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pquesLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 345, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(34, 34, 34)
                        .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(op1)
                            .add(op2))
                        .add(18, 18, 18)
                        .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(op3)
                            .add(op4))
                        .add(18, 18, 18)
                        .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bnext)
                            .add(bconfirm)))
                    .add(pquesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lb1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(lb2)))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout quesframeLayout = new org.jdesktop.layout.GroupLayout(quesframe.getContentPane());
        quesframe.getContentPane().setLayout(quesframeLayout);
        quesframeLayout.setHorizontalGroup(
            quesframeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, quesframeLayout.createSequentialGroup()
                .addContainerGap()
                .add(pques, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        quesframeLayout.setVerticalGroup(
            quesframeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, quesframeLayout.createSequentialGroup()
                .addContainerGap()
                .add(pques, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTRUCTIONS");

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("<html> <head> </head> <body> <h2>Quiz - Preliminary Round</h2><br><br><h3> 1.Only <b>two members</b> are allowed in a team.<br><br> 2.<b>25 </b>questions should be answered in <b>20 </b>minutes.<br><br> 3.The questions will be from <b>Current Affairs and Some Technical questions</b>.<br><br> 4.No negative marking.</h3><br><br> </body> </html>  ");

        bstart.setText("Start");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debugapp/images.GIF"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(bstart)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 382, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 108, Short.MAX_VALUE)
                .add(jLabel7)
                .add(66, 66, 66))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(78, 78, 78)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(bstart)
                        .add(262, 262, 262))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .add(362, 362, 362))))
        );

        org.jdesktop.layout.GroupLayout finstrLayout = new org.jdesktop.layout.GroupLayout(finstr.getContentPane());
        finstr.getContentPane().setLayout(finstrLayout);
        finstrLayout.setHorizontalGroup(
            finstrLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        finstrLayout.setVerticalGroup(
            finstrLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        bstart1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        bstart1.setText("TAKE THE TEST !!!!! ");
        bstart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstart1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/debugapp/untitled.JPG"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2Layout.createSequentialGroup()
                .add(324, 324, 324)
                .add(bstart1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 312, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(142, 142, 142)
                .add(bstart1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(289, 289, 289))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        // TODO add your handling code here:
        finstr.setVisible(false);
        quesframe.setSize(800, 600);
        quesframe.getContentPane().setBackground(Color.black);
        quesframe.getContentPane().setForeground(Color.white);
        quesframe.setVisible(true);

        tim = new javax.swing.Timer(1000, new Listen1());
        tim.start();


        int e = 0;

        while (e != 2) {
            int n = ran.nextInt(3);
            Integer n1 = new Integer(n);
            if (ts1.contains(n1)) {
                continue;

            } else {
                ts1.add(n1);
                e++;
            }
        }
        e = 0;
        while (e != 2) {
            int n = ran.nextInt(3);
            Integer n1 = new Integer(n);
            if (ts2.contains(n1)) {
                continue;

            } else {
                ts2.add(n1);
                e++;
            }
        }
        e = 0;
        while (e != 2) {
            int n = ran.nextInt(3);
            Integer n1 = new Integer(n);
            if (ts3.contains(n1)) {
                continue;

            } else {
                ts3.add(n1);
                e++;
            }
        }

        txtq.setText("Welcome to QUIZ PRELIMS in OZMENTA 08");

        System.out.println(ts1 + "" + ts2 + "" + ts3);
        it = ts1.iterator();
        curr = (Integer) it.next();
        try {
            s = con.prepareStatement("Select * from c where qno=?");
            s.setInt(1, curr.intValue());

            rs = s.executeQuery();
            rs.next();
            txtq.setText(rs.getString("ques"));
            op1.setText(rs.getString("o1"));
            op2.setText(rs.getString("o2"));
            op3.setText(rs.getString("o3"));
            op4.setText(rs.getString("o4"));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "2" + ex.getMessage());
        }
     
     
    }//GEN-LAST:event_bstartActionPerformed

    private void bconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bconfirmActionPerformed
        // TODO add your handling code here:

        if(flag==0)
        {
        try {
            s2 = con.prepareStatement("Select correct from c where qno=?");
            Integer i = Integer.parseInt(curr.toString());
            s2.setInt(1, i);

            rs = s2.executeQuery();
            rs.next();
            Integer ans = rs.getInt(1);
            if (op1.isSelected() && ans == 1) {
                score = score + 5;
            }
            if (op2.isSelected() && ans == 2) {
                score = score + 5;
            }
            if (op3.isSelected() && ans == 3) {
                score = score + 5;
            }
            if (op4.isSelected() && ans == 4) {
                score = score + 5;
            }


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }
        if(flag==1)
        {
            try {
            s2 = con.prepareStatement("Select correct from cpp where qno=?");
            Integer i = Integer.parseInt(curr.toString());
            s2.setInt(1, i);

            rs = s2.executeQuery();
            rs.next();
            Integer ans = rs.getInt(1);
            if (op1.isSelected() && ans == 1) {
                score = score + 5;
            }
            if (op2.isSelected() && ans == 2) {
                score = score + 5;
            }
            if (op3.isSelected() && ans == 3) {
                score = score + 5;
            }
            if (op4.isSelected() && ans == 4) {
                score = score + 5;
            }


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }
        if(flag==2)
        {
            try {
            s2 = con.prepareStatement("Select correct from java where qno=?");
            Integer i = Integer.parseInt(curr.toString());
            s2.setInt(1, i);

            rs = s2.executeQuery();
            rs.next();
            Integer ans = rs.getInt(1);
            if (op1.isSelected() && ans == 1) {
                score = score + 5;
            }
            if (op2.isSelected() && ans == 2) {
                score = score + 5;
            }
            if (op3.isSelected() && ans == 3) {
                score = score + 5;
            }
            if (op4.isSelected() && ans == 4) {
                score = score + 5;
            }


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        }
     
        
    }//GEN-LAST:event_bconfirmActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
       op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(false);
        if (flag == 0) {
            try {
                if (it.hasNext()) {
                    curr = (Integer) it.next();
                    s1 = con.prepareStatement("Select * from c where qno=?");

                    s1.setInt(1, curr.intValue());

                    rs = s1.executeQuery();
                    rs.next();
                    txtq.setText(rs.getString("ques"));
                    op1.setText(rs.getString("o1"));
                    op2.setText(rs.getString("o2"));
                    op3.setText(rs.getString("o3"));
                    op4.setText(rs.getString("o4"));

                } else {
                    flag = 1;
                    it=ts2.iterator();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "1" + ex.getMessage());
                
            }
        }
        if (flag == 1) {
            try {
                if (it.hasNext()) {

                    curr = (Integer) it.next();
                    s1 = con.prepareStatement("Select * from cpp where qno=?");

                    s1.setInt(1, curr.intValue());

                    rs = s1.executeQuery();
                    rs.next();
                    txtq.setText(rs.getString("ques"));
                    op1.setText(rs.getString("o1"));
                    op2.setText(rs.getString("o2"));
                    op3.setText(rs.getString("o3"));
                    op4.setText(rs.getString("o4"));

                } else {
                    flag = 2;
                    it=ts3.iterator();
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        if (flag == 2) {
            try {
                if (it.hasNext()) {
                    curr = (Integer)it.next();
                    s1 = con.prepareStatement("Select * from java where qno=?");

                    s1.setInt(1, curr.intValue());

                    rs = s1.executeQuery();
                    rs.next();
                    txtq.setText(rs.getString("ques"));
                    op1.setText(rs.getString("o1"));
                    op2.setText(rs.getString("o2"));
                    op3.setText(rs.getString("o3"));
                    op4.setText(rs.getString("o4"));

                } else {
                    try
                    {
                        s3.setInt(1, score);
                        s3.setString(2,name);
                        s3.executeUpdate();
                    }
                    catch(Exception ex1)
                    {
                        JOptionPane.showMessageDialog(null,ex1.getMessage());
                    }
                    JOptionPane.showMessageDialog(null, score+"Thanks for participating!!!!\nYour results will be announced by 1'O clock!!!");
                    quesframe.setVisible(false);
                    
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
     
        
    }//GEN-LAST:event_bnextActionPerformed

private void bstart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstart1ActionPerformed
//name=tname.getText();
        /*String id=tid.getText();
        String pass=new String(tpass.getPassword());
       System.out.println(tid.getText());*/
        System.out.println("hi");
       
        try {
            ps=con.prepareStatement("insert into debug.login(name,id,pass,score) values(?,?,?,?);");
            s3=con.prepareStatement("update debug.login set score=? where name=?;");
               /*name=tname.getText();
           String id=tid.getText();
           String pass=new String(tpass.getPassword());
            System.out.println(name+id+pass);
            ps.setString(1, name);
            ps.setString(2, id);
            ps.setString(3, pass);*/
            ps.setInt(4,0);
            ps.executeUpdate();
        }
        
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
        finstr.setSize(800,600);
        finstr.getContentPane().setBackground(Color.black);
        finstr.getContentPane().setForeground(Color.white);
        finstr.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_bstart1ActionPerformed

private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_op1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bconfirm;
    private javax.swing.JButton bnext;
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstart1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame finstr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JPanel pques;
    private javax.swing.JFrame quesframe;
    private javax.swing.JTextArea txtq;
    // End of variables declaration//GEN-END:variables
}
